service: docker-go-1.x-tests

plugins:
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: go1.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    handler: hello/main.go
    events:
      - http:
          method: get
          path: hello
          authorizer: authorizer

  authorizer:
    handler: authorizer/main.go
